# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 12:19
from __future__ import unicode_literals

from django.db import migrations
import ideia_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='book',
            name='text',
            field=ideia_summernote.fields.SummernoteField(),
        ),
    ]
